### ISSUE TITLE
Have a question about general types

### ISSUE THREAD

**Issue by wiwatsrt** [aqualaguna/shopee-client#3]
I 'm newbie Typescript, I have a question

I use this package with my project and typeorm I defined
```
@Entity()
export class Product {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  @IsNotEmpty()
  name: string;
```
And interface of this package

```
export interface Item {
    name: String;
    description: String;
```

Have error
`Type 'String' is not assignable to type 'string'.
  'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.`

I fixed
`product.sku = item.item_sku.toString();`

**Can you have suggest?**

I read from this
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

**Comment by aqualaguna** [comment]
yeah i already know that.
that is personally my beginner mistake.
String and string is not the same in typescript.
its like Class String and primitive string in c++.
this is the same case. as i already used String in many of my type definition. i will correct it shortly.

**Comment by wiwatsrt** [comment]
Thank you for develop this package.

**Comment by aqualaguna** [comment]
you're welcome
