### ISSUE TITLE
ShopeeClient is not defined

### ISSUE THREAD

**Issue by 987674712** [aqualaguna/shopee-client#6]
![1590685635(1)](https://user-images.githubusercontent.com/19771963/83171562-e29eda00-a148-11ea-9e72-c3a17be486cb.jpg)
var shopeeClient = require("shopee-client")
let client = new ShopeeClient({
  is_uat: false,
  shop_id: 'YOUR_SHOP_ID',
  partner_id: 'YOUR_PARTNER_ID',
  partner_key: 'YOUR_PARTNER_KEY'
})
let response = await client.image.uploadImage({
  images: [
    'https://i.picsum.photos/id/790/200/300.jpg'
  ]
});
console.log(response);

ReferenceError: ShopeeClient is not defined

Use npm to install, but this question is prompted after quotation, may I ask where I am not using it correctly?

**Comment by aqualaguna** [comment]
```
var shopeeClient = require("shopee-client") // dont forget case sensitive guys... :)shopeeClie
let client = new ShopeeClient({
is_uat: false,
shop_id: 'YOUR_SHOP_ID',
partner_id: 'YOUR_PARTNER_ID',
partner_key: 'YOUR_PARTNER_KEY'
})
```
should be:
`var ShopeeClient = require("shopee-client")`

**Comment by 987674712** [comment]
![image](https://user-images.githubusercontent.com/19771963/83222251-6fc64b00-a1aa-11ea-9528-07a41ca61b2f.png)
Sorry, I didn't pay attention when I copied, but the current "ShopeeClient is not a constructor", I tried to replace "exports.default = ShopeeClient;" with
"Module.exports = ShopeeClient;", the result is normal.
![image](https://user-images.githubusercontent.com/19771963/83222662-6b4e6200-a1ab-11ea-94bd-e009bc795e5c.png)
I personally think this may be caused by nodejs not supporting import. Please forgive me if it is inappropriate.
